import {
  cp,
  lstat,
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, extname } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const release = join(root, "release");
const marker = "musyg-contact-release-v1\n";
const serverFiles = ["index.mjs", "contact.mjs", "http.mjs"];
const publicExtensions = new Set([
  ".html",
  ".js",
  ".css",
  ".json",
  ".svg",
  ".png",
  ".jpg",
  ".jpeg",
  ".webp",
  ".ico",
  ".woff2",
  ".pdf",
  ".txt",
  ".xml",
]);

// Only replace a directory previously generated by this script. Never follow
// a symlink or erase an unrecognized directory supplied by a user.
try {
  const stat = await lstat(release);
  if (!stat.isDirectory() || stat.isSymbolicLink())
    throw new Error("Unsafe release directory");
  if ((await readFile(join(release, ".generated-release"), "utf8")) !== marker)
    throw new Error("Unrecognized release directory");
  await rm(release, { recursive: true });
} catch (error) {
  if (error.code !== "ENOENT") throw error;
  // An existing directory without our marker must not be reused.
  try {
    await lstat(release);
    throw new Error("Release directory has no generation marker");
  } catch (missing) {
    if (missing.code !== "ENOENT") throw missing;
  }
}
await mkdir(release);
await writeFile(join(release, ".generated-release"), marker);

async function copyRegularTree(source, destination, publicOnly = false) {
  if ((await lstat(source)).isSymbolicLink())
    throw new Error("Symlink rejected");
  await mkdir(destination, { recursive: true });
  for (const item of await readdir(source, { withFileTypes: true })) {
    if (item.isSymbolicLink()) throw new Error("Symlink rejected");
    if (item.name.startsWith(".")) continue;
    if (item.isDirectory())
      await copyRegularTree(
        join(source, item.name),
        join(destination, item.name),
        publicOnly,
      );
    else if (item.isFile()) {
      if (publicOnly && !publicExtensions.has(extname(item.name)))
        throw new Error("Unexpected public build file extension");
      await cp(join(source, item.name), join(destination, item.name));
    } else throw new Error("Non-regular build file");
  }
}

await copyRegularTree(join(root, "dist"), join(release, "dist"), true);
for (const required of ["index.html", "404.html"])
  await readFile(join(release, "dist", required));
await mkdir(join(release, "server"));
for (const name of serverFiles) {
  const source = join(root, "server", name);
  if (!(await lstat(source)).isFile() || (await lstat(source)).isSymbolicLink())
    throw new Error("Invalid server source");
  await cp(source, join(release, "server", name));
}
// Bundle the one server dependency from the already lockfile-installed tree.
// Fail closed if it ever gains dependencies that this packaging does not cover.
const sourcePackage = JSON.parse(
  await readFile(join(root, "package.json"), "utf8"),
);
const mailerRoot = join(root, "node_modules", "nodemailer");
const mailer = JSON.parse(
  await readFile(join(mailerRoot, "package.json"), "utf8"),
);
if (
  mailer.version !== sourcePackage.dependencies.nodemailer ||
  Object.keys(mailer.dependencies ?? {}).length ||
  Object.keys(mailer.optionalDependencies ?? {}).length ||
  Object.keys(mailer.peerDependencies ?? {}).length
)
  throw new Error("Unsupported Nodemailer dependency graph");
await copyRegularTree(mailerRoot, join(release, "node_modules", "nodemailer"));
await writeFile(
  join(release, "package.json"),
  JSON.stringify(
    {
      name: "musyg-contact-runtime",
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: { start: "node server/index.mjs" },
      dependencies: { nodemailer: mailer.version },
    },
    null,
    2,
  ) + "\n",
);
console.log(
  "Release prepared: server, prerendered dist and pinned Nodemailer; no environment files.",
);
